name: playlistdj
description: "A Flutter app for creating custom playlists with time sections and fades."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.5.0
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  path_provider: ^2.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  dio: ^5.3.2
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
